pipeline{
         agent any
         tools{
                  maven 'M2_HOME'
         }
         stages{
                  stage('sonar-scan'){
                           steps{
                                    withSonarQubeEnv('SonarQube'){
 sh 'mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=Ningendo7_geo-app'
                                    }
                                   
                           }
                  }
                  stage('maven'){
                          steps{ 
                           sh 'mvn clean validate compile install test package'
                  }
         }
         stage('docker login'){
                  steps{
                           sh 'aws ecr get-login-password --region us-east-1 | \
                           docker login --username AWS --password-stdin \
                           807906459006.dkr.ecr.us-east-1.amazonaws.com'
                  }
         }
                 
}
}