pipeline{
         agent any
         tools{
                  maven 'M2_HOME'
         }
         stages{
                  stage('sonar-scan'){
                           steps{
                                    withSonarQubeEnv('SonarQube'){
 sh 'mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=Ningendo7_geo-app'
                                    }
                                   
                           }
                  }
                  stage('maven'){
                          steps{ 
                           sh 'mvn clean validate compile install test package'
                  }
         }
         stage('docker login'){
                  steps{
                           sh 'aws ecr get-login-password --region us-east-1 | \
                           docker login --username AWS --password-stdin \
                           807906459006.dkr.ecr.us-east-1.amazonaws.com'
                  }
         }
         stage('docker build'){
                  steps{
                           sh 'docker build -t devops:v.${BUILD_ID} .'
                           sh 'docker build -t devops:latest .'
                  }
         }
         stage('Image tagging'){
        steps{
          sh 'docker tag devops:v.${BUILD_ID} \
          807906459006.dkr.ecr.us-east-1.amazonaws.com/devops:v.${BUILD_ID}'
          sh 'docker tag devops:latest \
          807906459006.dkr.ecr.us-east-1.amazonaws.com/devops:latest'
        }
    }
    stage('push image'){
        steps{  
       sh 'docker push 807906459006.dkr.ecr.us-east-1.amazonaws.com/devops:v.${BUILD_ID}'
       sh 'docker push 807906459006.dkr.ecr.us-east-1.amazonaws.com/devops:latest'
    }
    }
                 
}
}